### ISSUE TITLE
TLE/Base.hs:29:28: Not in scope: data constructor `TypeError'

### ISSUE THREAD

**Issue by deligeer** [enferex/TLESniff#1]
ghc -static -XTypeSynonymInstances -XFlexibleInstances -XUndecidableInstances -XScopedTypeVariables --make Main.hs -o tlesniff
[23 of 26] Compiling TLE.Base         ( TLE/Base.hs, TLE/Base.o )

TLE/Base.hs:29:28: Not in scope: data constructor `TypeError'
Makefile:6: recipe for target 'tlesniff' failed
make: *** [tlesniff] Error 1

**Comment by enferex** [comment]
Moved from a basic ghc build to Stack.
